FROM node:14.15.1-alpine as base
WORKDIR /app
ENV NODE_ENV development 
ENV CONFIG production
ENV PORT 80
RUN apk --no-cache add --virtual builds-deps build-base python 
COPY package*.json ./

FROM base as build
RUN npm install
COPY . ./
ENV NODE_ENV production 
RUN npm run build

FROM base as production
ENV NODE_ENV production 
RUN npm install
COPY . ./
COPY --from=build /app/.nuxt /app/.nuxt
EXPOSE 80
CMD [ "npm", "run", "start" ]