version: '3.7'

services:
  boord:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_HOST=localhost:3000
      - BROWSER_BASE_URL=http://localhost:3000
      - BASE_URL=http://localhost:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2.12
    restart: always
    command: mongod --quiet --logpath /dev/null
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb-data:
